// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file thirdfort/consumer/v1/resources.proto (package thirdfort.consumer.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Any, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thirdfort/consumer/v1/resources.proto.
 */
export const file_thirdfort_consumer_v1_resources: GenFile = /*@__PURE__*/
  fileDesc("CiV0aGlyZGZvcnQvY29uc3VtZXIvdjEvcmVzb3VyY2VzLnByb3RvEhV0aGlyZGZvcnQuY29uc3VtZXIudjEitQIKCFRhc2tTdGVwEgwKBG5hbWUYASABKAkSDAoEdHlwZRgCIAEoCRI0CgVzdGF0ZRgDIAEoDjIlLnRoaXJkZm9ydC5jb25zdW1lci52MS5UYXNrU3RlcC5TdGF0ZRIvCgtjcmVhdGVfdGltZRgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoLdXBkYXRlX3RpbWUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiQKBnBhcmFtcxgGIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkiTwoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIRCg1OT1RfQ09NUExFVEVEEAESDQoJQ09NUExFVEVEEAMSDQoJQ0FOQ0VMTEVEEARClAIKGWNvbS50aGlyZGZvcnQuY29uc3VtZXIudjFCDlJlc291cmNlc1Byb3RvUAFacWdpdGh1Yi5jb20vdGhpcmRmb3J0L3RoaXJkZm9ydC1tb2JpbGUtZnVsbHN0YWNrLWNvZGUtcmV2aWV3L3NlcnZlci9saWJzL2dlbnByb3RvL3RoaXJkZm9ydC9jb25zdW1lci92MTtjb25zdW1lcnYxogIDVENYqgIVVGhpcmRmb3J0LkNvbnN1bWVyLlYxygIVVGhpcmRmb3J0XENvbnN1bWVyXFYx4gIhVGhpcmRmb3J0XENvbnN1bWVyXFYxXEdQQk1ldGFkYXRh6gIXVGhpcmRmb3J0OjpDb25zdW1lcjo6VjFiBnByb3RvMw", [file_google_protobuf_any, file_google_protobuf_timestamp]);

/**
 * @generated from message thirdfort.consumer.v1.TaskStep
 */
export type TaskStep = Message<"thirdfort.consumer.v1.TaskStep"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: thirdfort.consumer.v1.TaskStep.State state = 3;
   */
  state: TaskStep_State;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 4;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 5;
   */
  updateTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Any params = 6;
   */
  params?: Any;
};

/**
 * Describes the message thirdfort.consumer.v1.TaskStep.
 * Use `create(TaskStepSchema)` to create a new message.
 */
export const TaskStepSchema: GenMessage<TaskStep> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_v1_resources, 0);

/**
 * @generated from enum thirdfort.consumer.v1.TaskStep.State
 */
export enum TaskStep_State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: NOT_COMPLETED = 1;
   */
  NOT_COMPLETED = 1,

  /**
   * @generated from enum value: COMPLETED = 3;
   */
  COMPLETED = 3,

  /**
   * @generated from enum value: CANCELLED = 4;
   */
  CANCELLED = 4,
}

/**
 * Describes the enum thirdfort.consumer.v1.TaskStep.State.
 */
export const TaskStep_StateSchema: GenEnum<TaskStep_State> = /*@__PURE__*/
  enumDesc(file_thirdfort_consumer_v1_resources, 0, 0);

