// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file thirdfort/consumer/v1/service.proto (package thirdfort.consumer.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { TaskStep, TaskStepSchema } from "./resources_pb";
import { file_thirdfort_consumer_v1_resources } from "./resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thirdfort/consumer/v1/service.proto.
 */
export const file_thirdfort_consumer_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiN0aGlyZGZvcnQvY29uc3VtZXIvdjEvc2VydmljZS5wcm90bxIVdGhpcmRmb3J0LmNvbnN1bWVyLnYxIiIKEkdldFRhc2tTdGVwUmVxdWVzdBIMCgRuYW1lGAEgASgJIksKF0NvbXBsZXRlVGFza1N0ZXBSZXF1ZXN0EgwKBG5hbWUYASABKAkSIgoEZGF0YRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkiXAoYQ29tcGxldGVUYXNrU3RlcFJlc3BvbnNlEgwKBG5hbWUYASABKAkSMgoJbmV4dF9zdGVwGAIgASgLMh8udGhpcmRmb3J0LmNvbnN1bWVyLnYxLlRhc2tTdGVwMuUBCg9Db25zdW1lclNlcnZpY2USWwoLR2V0VGFza1N0ZXASKS50aGlyZGZvcnQuY29uc3VtZXIudjEuR2V0VGFza1N0ZXBSZXF1ZXN0Gh8udGhpcmRmb3J0LmNvbnN1bWVyLnYxLlRhc2tTdGVwIgASdQoQQ29tcGxldGVUYXNrU3RlcBIuLnRoaXJkZm9ydC5jb25zdW1lci52MS5Db21wbGV0ZVRhc2tTdGVwUmVxdWVzdBovLnRoaXJkZm9ydC5jb25zdW1lci52MS5Db21wbGV0ZVRhc2tTdGVwUmVzcG9uc2UiAEKSAgoZY29tLnRoaXJkZm9ydC5jb25zdW1lci52MUIMU2VydmljZVByb3RvUAFacWdpdGh1Yi5jb20vdGhpcmRmb3J0L3RoaXJkZm9ydC1tb2JpbGUtZnVsbHN0YWNrLWNvZGUtcmV2aWV3L3NlcnZlci9saWJzL2dlbnByb3RvL3RoaXJkZm9ydC9jb25zdW1lci92MTtjb25zdW1lcnYxogIDVENYqgIVVGhpcmRmb3J0LkNvbnN1bWVyLlYxygIVVGhpcmRmb3J0XENvbnN1bWVyXFYx4gIhVGhpcmRmb3J0XENvbnN1bWVyXFYxXEdQQk1ldGFkYXRh6gIXVGhpcmRmb3J0OjpDb25zdW1lcjo6VjFiBnByb3RvMw", [file_google_protobuf_any, file_thirdfort_consumer_v1_resources]);

/**
 * @generated from message thirdfort.consumer.v1.GetTaskStepRequest
 */
export type GetTaskStepRequest = Message<"thirdfort.consumer.v1.GetTaskStepRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message thirdfort.consumer.v1.GetTaskStepRequest.
 * Use `create(GetTaskStepRequestSchema)` to create a new message.
 */
export const GetTaskStepRequestSchema: GenMessage<GetTaskStepRequest> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_v1_service, 0);

/**
 * @generated from message thirdfort.consumer.v1.CompleteTaskStepRequest
 */
export type CompleteTaskStepRequest = Message<"thirdfort.consumer.v1.CompleteTaskStepRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Any data = 2;
   */
  data?: Any;
};

/**
 * Describes the message thirdfort.consumer.v1.CompleteTaskStepRequest.
 * Use `create(CompleteTaskStepRequestSchema)` to create a new message.
 */
export const CompleteTaskStepRequestSchema: GenMessage<CompleteTaskStepRequest> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_v1_service, 1);

/**
 * @generated from message thirdfort.consumer.v1.CompleteTaskStepResponse
 */
export type CompleteTaskStepResponse = Message<"thirdfort.consumer.v1.CompleteTaskStepResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: thirdfort.consumer.v1.TaskStep next_step = 2;
   */
  nextStep?: TaskStep;
};

/**
 * Describes the message thirdfort.consumer.v1.CompleteTaskStepResponse.
 * Use `create(CompleteTaskStepResponseSchema)` to create a new message.
 */
export const CompleteTaskStepResponseSchema: GenMessage<CompleteTaskStepResponse> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_v1_service, 2);

/**
 * @generated from service thirdfort.consumer.v1.ConsumerService
 */
export const ConsumerService: GenService<{
  /**
   * Returns the requested [TaskStep][thirdfort.consumer.v1alpha1.TaskStep].
   *
   * @generated from rpc thirdfort.consumer.v1.ConsumerService.GetTaskStep
   */
  getTaskStep: {
    methodKind: "unary";
    input: typeof GetTaskStepRequestSchema;
    output: typeof TaskStepSchema;
  },
  /**
   * Completes the specified [TaskStep][thirdfort.consumer.v1alpha1.TaskStep] by providing the required data.
   *
   * @generated from rpc thirdfort.consumer.v1.ConsumerService.CompleteTaskStep
   */
  completeTaskStep: {
    methodKind: "unary";
    input: typeof CompleteTaskStepRequestSchema;
    output: typeof CompleteTaskStepResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_thirdfort_consumer_v1_service, 0);

