// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file thirdfort/consumer/v1/service.proto (package thirdfort.consumer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CompleteTaskStepRequest, CompleteTaskStepResponse, GetTaskStepRequest } from "./service_pb.js";
import { TaskStep } from "./resources_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service thirdfort.consumer.v1.ConsumerService
 */
export const ConsumerService = {
  typeName: "thirdfort.consumer.v1.ConsumerService",
  methods: {
    /**
     * Returns the requested [TaskStep][thirdfort.consumer.v1alpha1.TaskStep].
     *
     * @generated from rpc thirdfort.consumer.v1.ConsumerService.GetTaskStep
     */
    getTaskStep: {
      name: "GetTaskStep",
      I: GetTaskStepRequest,
      O: TaskStep,
      kind: MethodKind.Unary,
    },
    /**
     * Completes the specified [TaskStep][thirdfort.consumer.v1alpha1.TaskStep] by providing the required data.
     *
     * @generated from rpc thirdfort.consumer.v1.ConsumerService.CompleteTaskStep
     */
    completeTaskStep: {
      name: "CompleteTaskStep",
      I: CompleteTaskStepRequest,
      O: CompleteTaskStepResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

