// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file thirdfort/consumer/tasksteps/type/v1/task-description.proto (package thirdfort.consumer.tasksteps.type.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_thirdfort_consumer_v1_resources } from "../../../v1/resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thirdfort/consumer/tasksteps/type/v1/task-description.proto.
 */
export const file_thirdfort_consumer_tasksteps_type_v1_task_description: GenFile = /*@__PURE__*/
  fileDesc("Cjt0aGlyZGZvcnQvY29uc3VtZXIvdGFza3N0ZXBzL3R5cGUvdjEvdGFzay1kZXNjcmlwdGlvbi5wcm90bxIkdGhpcmRmb3J0LmNvbnN1bWVyLnRhc2tzdGVwcy50eXBlLnYxIpkBCh1UYXNrRGVzY3JpcHRpb25UYXNrU3RlcFBhcmFtcxIUCgxkaXNwbGF5X25hbWUYASABKAkSGwoTcHJpbWFyeV9kZXNjcmlwdGlvbhgCIAEoCRIdChVzZWNvbmRhcnlfZGVzY3JpcHRpb24YAyABKAkSFAoMcmVxdWlyZW1lbnRzGAQgAygJEhAKCHNraXBhYmxlGAUgASgIIi4KG1Rhc2tEZXNjcmlwdGlvblRhc2tTdGVwRGF0YRIPCgdza2lwcGVkGAEgASgIQvMCCihjb20udGhpcmRmb3J0LmNvbnN1bWVyLnRhc2tzdGVwcy50eXBlLnYxQhRUYXNrRGVzY3JpcHRpb25Qcm90b1ABWnxnaXRodWIuY29tL3RoaXJkZm9ydC90aGlyZGZvcnQtbW9iaWxlLWZ1bGxzdGFjay1jb2RlLXJldmlldy9zZXJ2ZXIvbGlicy9nZW5wcm90by90aGlyZGZvcnQvY29uc3VtZXIvdGFza3N0ZXBzL3R5cGUvdjE7dHlwZXYxogIEVENUVKoCJFRoaXJkZm9ydC5Db25zdW1lci5UYXNrc3RlcHMuVHlwZS5WMcoCJFRoaXJkZm9ydFxDb25zdW1lclxUYXNrc3RlcHNcVHlwZVxWMeICMFRoaXJkZm9ydFxDb25zdW1lclxUYXNrc3RlcHNcVHlwZVxWMVxHUEJNZXRhZGF0YeoCKFRoaXJkZm9ydDo6Q29uc3VtZXI6OlRhc2tzdGVwczo6VHlwZTo6VjFiBnByb3RvMw", [file_thirdfort_consumer_v1_resources]);

/**
 * @generated from message thirdfort.consumer.tasksteps.type.v1.TaskDescriptionTaskStepParams
 */
export type TaskDescriptionTaskStepParams = Message<"thirdfort.consumer.tasksteps.type.v1.TaskDescriptionTaskStepParams"> & {
  /**
   * The display name of the task.
   *
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * The description of the task.
   *
   * @generated from field: string primary_description = 2;
   */
  primaryDescription: string;

  /**
   * The secondary description of the task.
   *
   * @generated from field: string secondary_description = 3;
   */
  secondaryDescription: string;

  /**
   * A list of things the user must know/gather in order to complete this task.
   *
   * @generated from field: repeated string requirements = 4;
   */
  requirements: string[];

  /**
   * Indicates if this task is skipable.
   *
   * @generated from field: bool skipable = 5;
   */
  skipable: boolean;
};

/**
 * Describes the message thirdfort.consumer.tasksteps.type.v1.TaskDescriptionTaskStepParams.
 * Use `create(TaskDescriptionTaskStepParamsSchema)` to create a new message.
 */
export const TaskDescriptionTaskStepParamsSchema: GenMessage<TaskDescriptionTaskStepParams> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_tasksteps_type_v1_task_description, 0);

/**
 * @generated from message thirdfort.consumer.tasksteps.type.v1.TaskDescriptionTaskStepData
 */
export type TaskDescriptionTaskStepData = Message<"thirdfort.consumer.tasksteps.type.v1.TaskDescriptionTaskStepData"> & {
  /**
   * Indicates whether the task was skipped.
   *
   * @generated from field: bool skipped = 1;
   */
  skipped: boolean;
};

/**
 * Describes the message thirdfort.consumer.tasksteps.type.v1.TaskDescriptionTaskStepData.
 * Use `create(TaskDescriptionTaskStepDataSchema)` to create a new message.
 */
export const TaskDescriptionTaskStepDataSchema: GenMessage<TaskDescriptionTaskStepData> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_tasksteps_type_v1_task_description, 1);

