// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file thirdfort/consumer/tasksteps/type/v1/task-information.proto (package thirdfort.consumer.tasksteps.type.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_thirdfort_consumer_v1_resources } from "../../../v1/resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thirdfort/consumer/tasksteps/type/v1/task-information.proto.
 */
export const file_thirdfort_consumer_tasksteps_type_v1_task_information: GenFile = /*@__PURE__*/
  fileDesc("Cjt0aGlyZGZvcnQvY29uc3VtZXIvdGFza3N0ZXBzL3R5cGUvdjEvdGFzay1pbmZvcm1hdGlvbi5wcm90bxIkdGhpcmRmb3J0LmNvbnN1bWVyLnRhc2tzdGVwcy50eXBlLnYxIoYBCh1UYXNrSW5mb3JtYXRpb25UYXNrU3RlcFBhcmFtcxIUCgxkaXNwbGF5X25hbWUYASABKAkSGwoTcHJpbWFyeV9kZXNjcmlwdGlvbhgCIAEoCRIdChVzZWNvbmRhcnlfZGVzY3JpcHRpb24YAyABKAkSEwoLYnV0dG9uX3RleHQYBCABKAkiHQobVGFza0luZm9ybWF0aW9uVGFza1N0ZXBEYXRhQvMCCihjb20udGhpcmRmb3J0LmNvbnN1bWVyLnRhc2tzdGVwcy50eXBlLnYxQhRUYXNrSW5mb3JtYXRpb25Qcm90b1ABWnxnaXRodWIuY29tL3RoaXJkZm9ydC90aGlyZGZvcnQtbW9iaWxlLWZ1bGxzdGFjay1jb2RlLXJldmlldy9zZXJ2ZXIvbGlicy9nZW5wcm90by90aGlyZGZvcnQvY29uc3VtZXIvdGFza3N0ZXBzL3R5cGUvdjE7dHlwZXYxogIEVENUVKoCJFRoaXJkZm9ydC5Db25zdW1lci5UYXNrc3RlcHMuVHlwZS5WMcoCJFRoaXJkZm9ydFxDb25zdW1lclxUYXNrc3RlcHNcVHlwZVxWMeICMFRoaXJkZm9ydFxDb25zdW1lclxUYXNrc3RlcHNcVHlwZVxWMVxHUEJNZXRhZGF0YeoCKFRoaXJkZm9ydDo6Q29uc3VtZXI6OlRhc2tzdGVwczo6VHlwZTo6VjFiBnByb3RvMw", [file_thirdfort_consumer_v1_resources]);

/**
 * This task step is used to display information to the user.
 *
 * @generated from message thirdfort.consumer.tasksteps.type.v1.TaskInformationTaskStepParams
 */
export type TaskInformationTaskStepParams = Message<"thirdfort.consumer.tasksteps.type.v1.TaskInformationTaskStepParams"> & {
  /**
   * The display name of the task.
   *
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * The description of the task.
   *
   * @generated from field: string primary_description = 2;
   */
  primaryDescription: string;

  /**
   * The secondary description of the task.
   *
   * @generated from field: string secondary_description = 3;
   */
  secondaryDescription: string;

  /**
   * The text to display on the button used to continue to the next task.
   *
   * @generated from field: string button_text = 4;
   */
  buttonText: string;
};

/**
 * Describes the message thirdfort.consumer.tasksteps.type.v1.TaskInformationTaskStepParams.
 * Use `create(TaskInformationTaskStepParamsSchema)` to create a new message.
 */
export const TaskInformationTaskStepParamsSchema: GenMessage<TaskInformationTaskStepParams> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_tasksteps_type_v1_task_information, 0);

/**
 * @generated from message thirdfort.consumer.tasksteps.type.v1.TaskInformationTaskStepData
 */
export type TaskInformationTaskStepData = Message<"thirdfort.consumer.tasksteps.type.v1.TaskInformationTaskStepData"> & {
};

/**
 * Describes the message thirdfort.consumer.tasksteps.type.v1.TaskInformationTaskStepData.
 * Use `create(TaskInformationTaskStepDataSchema)` to create a new message.
 */
export const TaskInformationTaskStepDataSchema: GenMessage<TaskInformationTaskStepData> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_tasksteps_type_v1_task_information, 1);

