// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file thirdfort/consumer/tasksteps/type/v1/task-completion.proto (package thirdfort.consumer.tasksteps.type.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_thirdfort_consumer_v1_resources } from "../../../v1/resources_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thirdfort/consumer/tasksteps/type/v1/task-completion.proto.
 */
export const file_thirdfort_consumer_tasksteps_type_v1_task_completion: GenFile = /*@__PURE__*/
  fileDesc("Cjp0aGlyZGZvcnQvY29uc3VtZXIvdGFza3N0ZXBzL3R5cGUvdjEvdGFzay1jb21wbGV0aW9uLnByb3RvEiR0aGlyZGZvcnQuY29uc3VtZXIudGFza3N0ZXBzLnR5cGUudjEibQocVGFza0NvbXBsZXRpb25UYXNrU3RlcFBhcmFtcxIUCgxkaXNwbGF5X25hbWUYASABKAkSGwoTcHJpbWFyeV9kZXNjcmlwdGlvbhgCIAEoCRIaChJzdWJtaXRfYnV0dG9uX3RleHQYAyABKAkiHAoaVGFza0NvbXBsZXRpb25UYXNrU3RlcERhdGFC8gIKKGNvbS50aGlyZGZvcnQuY29uc3VtZXIudGFza3N0ZXBzLnR5cGUudjFCE1Rhc2tDb21wbGV0aW9uUHJvdG9QAVp8Z2l0aHViLmNvbS90aGlyZGZvcnQvdGhpcmRmb3J0LW1vYmlsZS1mdWxsc3RhY2stY29kZS1yZXZpZXcvc2VydmVyL2xpYnMvZ2VucHJvdG8vdGhpcmRmb3J0L2NvbnN1bWVyL3Rhc2tzdGVwcy90eXBlL3YxO3R5cGV2MaICBFRDVFSqAiRUaGlyZGZvcnQuQ29uc3VtZXIuVGFza3N0ZXBzLlR5cGUuVjHKAiRUaGlyZGZvcnRcQ29uc3VtZXJcVGFza3N0ZXBzXFR5cGVcVjHiAjBUaGlyZGZvcnRcQ29uc3VtZXJcVGFza3N0ZXBzXFR5cGVcVjFcR1BCTWV0YWRhdGHqAihUaGlyZGZvcnQ6OkNvbnN1bWVyOjpUYXNrc3RlcHM6OlR5cGU6OlYxYgZwcm90bzM", [file_thirdfort_consumer_v1_resources]);

/**
 * @generated from message thirdfort.consumer.tasksteps.type.v1.TaskCompletionTaskStepParams
 */
export type TaskCompletionTaskStepParams = Message<"thirdfort.consumer.tasksteps.type.v1.TaskCompletionTaskStepParams"> & {
  /**
   * The display name of the task.
   *
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * The description of the task.
   *
   * @generated from field: string primary_description = 2;
   */
  primaryDescription: string;

  /**
   * The text to display on the submit button.
   *
   * @generated from field: string submit_button_text = 3;
   */
  submitButtonText: string;
};

/**
 * Describes the message thirdfort.consumer.tasksteps.type.v1.TaskCompletionTaskStepParams.
 * Use `create(TaskCompletionTaskStepParamsSchema)` to create a new message.
 */
export const TaskCompletionTaskStepParamsSchema: GenMessage<TaskCompletionTaskStepParams> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_tasksteps_type_v1_task_completion, 0);

/**
 * @generated from message thirdfort.consumer.tasksteps.type.v1.TaskCompletionTaskStepData
 */
export type TaskCompletionTaskStepData = Message<"thirdfort.consumer.tasksteps.type.v1.TaskCompletionTaskStepData"> & {
};

/**
 * Describes the message thirdfort.consumer.tasksteps.type.v1.TaskCompletionTaskStepData.
 * Use `create(TaskCompletionTaskStepDataSchema)` to create a new message.
 */
export const TaskCompletionTaskStepDataSchema: GenMessage<TaskCompletionTaskStepData> = /*@__PURE__*/
  messageDesc(file_thirdfort_consumer_tasksteps_type_v1_task_completion, 1);

