// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: thirdfort/consumer/v1/service.proto

package consumerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/thirdfort/thirdfort-mobile-fullstack-code-review/server/libs/genproto/thirdfort/consumer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConsumerServiceName is the fully-qualified name of the ConsumerService service.
	ConsumerServiceName = "thirdfort.consumer.v1.ConsumerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConsumerServiceGetTaskStepProcedure is the fully-qualified name of the ConsumerService's
	// GetTaskStep RPC.
	ConsumerServiceGetTaskStepProcedure = "/thirdfort.consumer.v1.ConsumerService/GetTaskStep"
	// ConsumerServiceCompleteTaskStepProcedure is the fully-qualified name of the ConsumerService's
	// CompleteTaskStep RPC.
	ConsumerServiceCompleteTaskStepProcedure = "/thirdfort.consumer.v1.ConsumerService/CompleteTaskStep"
)

// ConsumerServiceClient is a client for the thirdfort.consumer.v1.ConsumerService service.
type ConsumerServiceClient interface {
	// Returns the requested [TaskStep][thirdfort.consumer.v1alpha1.TaskStep].
	GetTaskStep(context.Context, *connect.Request[v1.GetTaskStepRequest]) (*connect.Response[v1.TaskStep], error)
	// Completes the specified [TaskStep][thirdfort.consumer.v1alpha1.TaskStep] by providing the required data.
	CompleteTaskStep(context.Context, *connect.Request[v1.CompleteTaskStepRequest]) (*connect.Response[v1.CompleteTaskStepResponse], error)
}

// NewConsumerServiceClient constructs a client for the thirdfort.consumer.v1.ConsumerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConsumerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConsumerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	consumerServiceMethods := v1.File_thirdfort_consumer_v1_service_proto.Services().ByName("ConsumerService").Methods()
	return &consumerServiceClient{
		getTaskStep: connect.NewClient[v1.GetTaskStepRequest, v1.TaskStep](
			httpClient,
			baseURL+ConsumerServiceGetTaskStepProcedure,
			connect.WithSchema(consumerServiceMethods.ByName("GetTaskStep")),
			connect.WithClientOptions(opts...),
		),
		completeTaskStep: connect.NewClient[v1.CompleteTaskStepRequest, v1.CompleteTaskStepResponse](
			httpClient,
			baseURL+ConsumerServiceCompleteTaskStepProcedure,
			connect.WithSchema(consumerServiceMethods.ByName("CompleteTaskStep")),
			connect.WithClientOptions(opts...),
		),
	}
}

// consumerServiceClient implements ConsumerServiceClient.
type consumerServiceClient struct {
	getTaskStep      *connect.Client[v1.GetTaskStepRequest, v1.TaskStep]
	completeTaskStep *connect.Client[v1.CompleteTaskStepRequest, v1.CompleteTaskStepResponse]
}

// GetTaskStep calls thirdfort.consumer.v1.ConsumerService.GetTaskStep.
func (c *consumerServiceClient) GetTaskStep(ctx context.Context, req *connect.Request[v1.GetTaskStepRequest]) (*connect.Response[v1.TaskStep], error) {
	return c.getTaskStep.CallUnary(ctx, req)
}

// CompleteTaskStep calls thirdfort.consumer.v1.ConsumerService.CompleteTaskStep.
func (c *consumerServiceClient) CompleteTaskStep(ctx context.Context, req *connect.Request[v1.CompleteTaskStepRequest]) (*connect.Response[v1.CompleteTaskStepResponse], error) {
	return c.completeTaskStep.CallUnary(ctx, req)
}

// ConsumerServiceHandler is an implementation of the thirdfort.consumer.v1.ConsumerService service.
type ConsumerServiceHandler interface {
	// Returns the requested [TaskStep][thirdfort.consumer.v1alpha1.TaskStep].
	GetTaskStep(context.Context, *connect.Request[v1.GetTaskStepRequest]) (*connect.Response[v1.TaskStep], error)
	// Completes the specified [TaskStep][thirdfort.consumer.v1alpha1.TaskStep] by providing the required data.
	CompleteTaskStep(context.Context, *connect.Request[v1.CompleteTaskStepRequest]) (*connect.Response[v1.CompleteTaskStepResponse], error)
}

// NewConsumerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConsumerServiceHandler(svc ConsumerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	consumerServiceMethods := v1.File_thirdfort_consumer_v1_service_proto.Services().ByName("ConsumerService").Methods()
	consumerServiceGetTaskStepHandler := connect.NewUnaryHandler(
		ConsumerServiceGetTaskStepProcedure,
		svc.GetTaskStep,
		connect.WithSchema(consumerServiceMethods.ByName("GetTaskStep")),
		connect.WithHandlerOptions(opts...),
	)
	consumerServiceCompleteTaskStepHandler := connect.NewUnaryHandler(
		ConsumerServiceCompleteTaskStepProcedure,
		svc.CompleteTaskStep,
		connect.WithSchema(consumerServiceMethods.ByName("CompleteTaskStep")),
		connect.WithHandlerOptions(opts...),
	)
	return "/thirdfort.consumer.v1.ConsumerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConsumerServiceGetTaskStepProcedure:
			consumerServiceGetTaskStepHandler.ServeHTTP(w, r)
		case ConsumerServiceCompleteTaskStepProcedure:
			consumerServiceCompleteTaskStepHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConsumerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConsumerServiceHandler struct{}

func (UnimplementedConsumerServiceHandler) GetTaskStep(context.Context, *connect.Request[v1.GetTaskStepRequest]) (*connect.Response[v1.TaskStep], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thirdfort.consumer.v1.ConsumerService.GetTaskStep is not implemented"))
}

func (UnimplementedConsumerServiceHandler) CompleteTaskStep(context.Context, *connect.Request[v1.CompleteTaskStepRequest]) (*connect.Response[v1.CompleteTaskStepResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thirdfort.consumer.v1.ConsumerService.CompleteTaskStep is not implemented"))
}
